// ============================================================
// 2026 World Cup — Squad data for all 48 teams
// Key players with positions, numbers, and tournament goals
// ============================================================

const SQUADS = {

  // Group A
  MEX: { coach:"Jaime Lozano", formation:"4-3-3", players:[
    { name:"Guillermo Ochoa", pos:"GK", num:13, goals:0 },
    { name:"Edson Álvarez", pos:"DM", num:4, goals:0 },
    { name:"Luis Chávez", pos:"CM", num:8, goals:0 },
    { name:"Orbelín Pineda", pos:"CM", num:17, goals:0 },
    { name:"Julián Quiñones", pos:"LW", num:20, goals:1 },
    { name:"Raúl Jiménez", pos:"ST", num:9, goals:1 },
    { name:"Santiago Gimenez", pos:"ST", num:11, goals:0 },
    { name:"Hirving Lozano", pos:"RW", num:22, goals:0 },
    { name:"César Montes", pos:"CB", num:3, goals:0 },
    { name:"Johan Vásquez", pos:"CB", num:5, goals:0 },
    { name:"Jorge Sánchez", pos:"RB", num:2, goals:0 },
    { name:"Jesús Gallardo", pos:"LB", num:6, goals:0 },
    { name:"Brian Gutiérrez", pos:"AM", num:10, goals:0 },
    { name:"Carlos Rodríguez", pos:"CM", num:7, goals:0 },
    { name:"Roberto Alvarado", pos:"RW", num:15, goals:0 },
  ]},
  RSA: { coach:"Hugo Broos", formation:"4-2-3-1", players:[
    { name:"Ronwen Williams", pos:"GK", num:1, goals:0 },
    { name:"Lyle Foster", pos:"ST", num:9, goals:0 },
    { name:"Themba Zwane", pos:"AM", num:10, goals:0 },
    { name:"Sphephelo Sithole", pos:"CM", num:6, goals:0 },
    { name:"Percy Tau", pos:"RW", num:11, goals:0 },
    { name:"Mothobi Mvala", pos:"CB", num:4, goals:0 },
    { name:"Khuliso Mudau", pos:"RB", num:2, goals:0 },
    { name:"Aubrey Modiba", pos:"LB", num:5, goals:0 },
    { name:"Teboho Mokoena", pos:"CM", num:8, goals:0 },
    { name:"Evidence Makgopa", pos:"ST", num:12, goals:0 },
  ]},
  KOR: { coach:"Hong Myung-bo", formation:"4-2-3-1", players:[
    { name:"Kim Seung-gyu", pos:"GK", num:1, goals:0 },
    { name:"Kim Min-jae", pos:"CB", num:4, goals:0 },
    { name:"Son Heung-min", pos:"LW", num:7, goals:0 },
    { name:"Lee Kang-in", pos:"AM", num:18, goals:0 },
    { name:"Hwang Hee-chan", pos:"RW", num:11, goals:0 },
    { name:"Hwang In-beom", pos:"CM", num:6, goals:1 },
    { name:"Oh Hyeon-gyu", pos:"ST", num:9, goals:1 },
    { name:"Lee Jae-sung", pos:"CM", num:10, goals:0 },
    { name:"Kim Young-gwon", pos:"CB", num:19, goals:0 },
    { name:"Seol Young-woo", pos:"RB", num:2, goals:0 },
    { name:"Lee Ki-je", pos:"LB", num:3, goals:0 },
    { name:"Cho Gue-sung", pos:"ST", num:16, goals:0 },
    { name:"Jung Woo-young", pos:"DM", num:5, goals:0 },
  ]},
  CZE: { coach:"Ivan Hašek", formation:"3-5-2", players:[
    { name:"Tomáš Souček", pos:"CM", num:8, goals:0 },
    { name:"Patrik Schick", pos:"ST", num:10, goals:0 },
    { name:"Vladimír Coufal", pos:"RWB", num:5, goals:0 },
    { name:"Ladislav Krejčí", pos:"CB", num:3, goals:1 },
    { name:"Antonín Barák", pos:"AM", num:7, goals:0 },
    { name:"Adam Hložek", pos:"FW", num:9, goals:0 },
    { name:"Matěj Jurásek", pos:"GK", num:1, goals:0 },
    { name:"David Jurásek", pos:"LWB", num:14, goals:0 },
    { name:"Tomáš Holeš", pos:"CB", num:4, goals:0 },
    { name:"Michal Sadílek", pos:"CM", num:15, goals:0 },
  ]},

  // Group B
  CAN: { coach:"Jesse Marsch", formation:"4-4-2", players:[
    { name:"Alphonso Davies", pos:"LB", num:19, goals:0 },
    { name:"Jonathan David", pos:"ST", num:10, goals:0 },
    { name:"Stephen Eustáquio", pos:"CM", num:7, goals:0 },
    { name:"Cyle Larin", pos:"ST", num:9, goals:0 },
    { name:"Tajon Buchanan", pos:"RW", num:11, goals:0 },
    { name:"Ismaël Koné", pos:"CM", num:8, goals:0 },
    { name:"Alistair Johnston", pos:"RB", num:2, goals:0 },
    { name:"Derek Cornelius", pos:"CB", num:4, goals:0 },
    { name:"Maxime Crépeau", pos:"GK", num:1, goals:0 },
    { name:"Jonathan Osorio", pos:"CM", num:21, goals:0 },
  ]},
  BIH: { coach:"Sergej Barbarez", formation:"4-2-3-1", players:[
    { name:"Edin Džeko", pos:"ST", num:11, goals:0 },
    { name:"Sead Kolašinac", pos:"LB", num:5, goals:0 },
    { name:"Ermedin Demirović", pos:"ST", num:9, goals:0 },
    { name:"Miralem Pjanić", pos:"CM", num:10, goals:0 },
    { name:"Anel Ahmedhodžić", pos:"CB", num:3, goals:0 },
    { name:"Rade Krunić", pos:"CM", num:14, goals:0 },
    { name:"Amar Dedić", pos:"RB", num:2, goals:0 },
    { name:"Ibrahim Šehić", pos:"GK", num:1, goals:0 },
  ]},
  QAT: { coach:"Julen Lopetegui", formation:"4-3-3", players:[
    { name:"Almoez Ali", pos:"ST", num:11, goals:0 },
    { name:"Akram Afif", pos:"LW", num:10, goals:0 },
    { name:"Hassan Al-Haydos", pos:"RW", num:8, goals:0 },
    { name:"Abdulaziz Hatem", pos:"CM", num:6, goals:0 },
    { name:"Boualem Khoukhi", pos:"CB", num:4, goals:0 },
    { name:"Meshaal Barsham", pos:"GK", num:1, goals:0 },
    { name:"Mohammed Waad", pos:"RB", num:2, goals:0 },
    { name:"Tarek Salman", pos:"CB", num:5, goals:0 },
    { name:"Homam Ahmed", pos:"LB", num:3, goals:0 },
    { name:"Karim Boudiaf", pos:"DM", num:12, goals:0 },
  ]},
  SUI: { coach:"Murat Yakin", formation:"4-2-3-1", players:[
    { name:"Gregor Kobel", pos:"GK", num:1, goals:0 },
    { name:"Manuel Akanji", pos:"CB", num:5, goals:0 },
    { name:"Granit Xhaka", pos:"CM", num:10, goals:0 },
    { name:"Breel Embolo", pos:"ST", num:9, goals:0 },
    { name:"Remo Freuler", pos:"CM", num:8, goals:0 },
    { name:"Ruben Vargas", pos:"LW", num:17, goals:0 },
    { name:"Xherdan Shaqiri", pos:"RW", num:23, goals:0 },
    { name:"Ricardo Rodriguez", pos:"LB", num:13, goals:0 },
    { name:"Nico Elvedi", pos:"CB", num:4, goals:0 },
    { name:"Silvan Widmer", pos:"RB", num:3, goals:0 },
    { name:"Denis Zakaria", pos:"DM", num:6, goals:0 },
    { name:"Noah Okafor", pos:"FW", num:7, goals:0 },
  ]},

  // Group C
  BRA: { coach:"Carlo Ancelotti", formation:"4-2-3-1", players:[
    { name:"Alisson", pos:"GK", num:1, goals:0 },
    { name:"Marquinhos", pos:"CB", num:4, goals:0 },
    { name:"Gabriel Magalhães", pos:"CB", num:14, goals:0 },
    { name:"Casemiro", pos:"DM", num:5, goals:0 },
    { name:"Bruno Guimarães", pos:"CM", num:8, goals:0 },
    { name:"Vinícius Jr.", pos:"LW", num:7, goals:0 },
    { name:"Neymar", pos:"AM", num:10, goals:0 },
    { name:"Raphinha", pos:"RW", num:11, goals:0 },
    { name:"Matheus Cunha", pos:"ST", num:9, goals:0 },
    { name:"Rodrygo", pos:"FW", num:21, goals:0 },
    { name:"Gabriel Martinelli", pos:"FW", num:22, goals:0 },
    { name:"Endrick", pos:"ST", num:19, goals:0 },
    { name:"Éder Militão", pos:"CB", num:3, goals:0 },
    { name:"Danilo", pos:"RB", num:2, goals:0 },
    { name:"Guilherme Arana", pos:"LB", num:6, goals:0 },
  ]},
  MAR: { coach:"Walid Regragui", formation:"4-3-3", players:[
    { name:"Yassine Bounou", pos:"GK", num:1, goals:0 },
    { name:"Achraf Hakimi", pos:"RB", num:2, goals:0 },
    { name:"Noussair Mazraoui", pos:"LB", num:3, goals:0 },
    { name:"Romain Saïss", pos:"CB", num:6, goals:0 },
    { name:"Nayef Aguerd", pos:"CB", num:5, goals:0 },
    { name:"Sofyan Amrabat", pos:"DM", num:4, goals:0 },
    { name:"Brahim Díaz", pos:"AM", num:10, goals:0 },
    { name:"Azzedine Ounahi", pos:"CM", num:8, goals:0 },
    { name:"Hakim Ziyech", pos:"RW", num:7, goals:0 },
    { name:"Youssef En-Nesyri", pos:"ST", num:9, goals:0 },
    { name:"Amine Adli", pos:"LW", num:17, goals:0 },
    { name:"Abde Ezzalzouli", pos:"FW", num:16, goals:0 },
  ]},
  HAI: { coach:"Sébastien Migné", formation:"4-4-2", players:[
    { name:"Duckens Nazon", pos:"ST", num:9, goals:0 },
    { name:"Wilson Isidor", pos:"ST", num:11, goals:0 },
    { name:"Jean-Ricner Bellegarde", pos:"CM", num:8, goals:0 },
    { name:"Derrick Etienne", pos:"LW", num:7, goals:0 },
    { name:"Frantzdy Pierrot", pos:"ST", num:20, goals:0 },
    { name:"Carlens Arcus", pos:"RB", num:2, goals:0 },
    { name:"Ricardo Adé", pos:"CB", num:4, goals:0 },
    { name:"Johny Placide", pos:"GK", num:1, goals:0 },
  ]},
  SCO: { coach:"Steve Clarke", formation:"3-4-2-1", players:[
    { name:"Craig Gordon", pos:"GK", num:1, goals:0 },
    { name:"Andy Robertson", pos:"LWB", num:3, goals:0 },
    { name:"Kieran Tierney", pos:"CB", num:6, goals:0 },
    { name:"Scott McTominay", pos:"CM", num:4, goals:0 },
    { name:"John McGinn", pos:"AM", num:7, goals:0 },
    { name:"Billy Gilmour", pos:"CM", num:14, goals:0 },
    { name:"Ché Adams", pos:"ST", num:10, goals:0 },
    { name:"Ryan Christie", pos:"FW", num:11, goals:0 },
    { name:"Nathan Patterson", pos:"RWB", num:2, goals:0 },
    { name:"Jack Hendry", pos:"CB", num:5, goals:0 },
    { name:"Ryan Porteous", pos:"CB", num:15, goals:0 },
    { name:"Lewis Ferguson", pos:"CM", num:19, goals:0 },
  ]},

  // Group D
  USA: { coach:"Mauricio Pochettino", formation:"4-3-3", players:[
    { name:"Matt Turner", pos:"GK", num:1, goals:0 },
    { name:"Antonee Robinson", pos:"LB", num:5, goals:0 },
    { name:"Tim Ream", pos:"CB", num:3, goals:0 },
    { name:"Chris Richards", pos:"CB", num:4, goals:0 },
    { name:"Sergiño Dest", pos:"RB", num:2, goals:0 },
    { name:"Weston McKennie", pos:"CM", num:8, goals:0 },
    { name:"Yunus Musah", pos:"CM", num:6, goals:0 },
    { name:"Gio Reyna", pos:"AM", num:7, goals:0 },
    { name:"Christian Pulisic", pos:"LW", num:10, goals:0 },
    { name:"Tim Weah", pos:"RW", num:21, goals:0 },
    { name:"Folarin Balogun", pos:"ST", num:9, goals:0 },
    { name:"Ricardo Pepi", pos:"ST", num:14, goals:0 },
    { name:"Tyler Adams", pos:"DM", num:15, goals:0 },
    { name:"Brenden Aaronson", pos:"FW", num:11, goals:0 },
  ]},
  PAR: { coach:"Daniel Garnero", formation:"4-2-3-1", players:[
    { name:"Miguel Almirón", pos:"AM", num:10, goals:0 },
    { name:"Julio Enciso", pos:"FW", num:19, goals:0 },
    { name:"Gustavo Gómez", pos:"CB", num:15, goals:0 },
    { name:"Ramón Sosa", pos:"LW", num:17, goals:0 },
    { name:"Antonio Sanabria", pos:"ST", num:9, goals:0 },
    { name:"Mathías Villasanti", pos:"CM", num:8, goals:0 },
    { name:"Fabián Balbuena", pos:"CB", num:5, goals:0 },
    { name:"Santiago Rojas", pos:"GK", num:1, goals:0 },
  ]},
  AUS: { coach:"Tony Popovic", formation:"4-4-2", players:[
    { name:"Mathew Ryan", pos:"GK", num:1, goals:0 },
    { name:"Harry Souttar", pos:"CB", num:4, goals:0 },
    { name:"Nestory Irankunda", pos:"RW", num:20, goals:0 },
    { name:"Jackson Irvine", pos:"CM", num:8, goals:0 },
    { name:"Riley McGree", pos:"AM", num:14, goals:0 },
    { name:"Craig Goodwin", pos:"LW", num:11, goals:0 },
    { name:"Mitchell Duke", pos:"ST", num:9, goals:0 },
    { name:"Kye Rowles", pos:"CB", num:3, goals:0 },
    { name:"Nathaniel Atkinson", pos:"RB", num:2, goals:0 },
    { name:"Aziz Behich", pos:"LB", num:16, goals:0 },
  ]},
  TUR: { coach:"Vincenzo Montella", formation:"4-2-3-1", players:[
    { name:"Hakan Çalhanoğlu", pos:"CM", num:10, goals:0 },
    { name:"Arda Güler", pos:"AM", num:8, goals:0 },
    { name:"Kenan Yıldız", pos:"LW", num:19, goals:0 },
    { name:"Barış Alper Yılmaz", pos:"RW", num:7, goals:0 },
    { name:"Cenk Tosun", pos:"ST", num:9, goals:0 },
    { name:"Orkun Kökçü", pos:"CM", num:6, goals:0 },
    { name:"Merih Demiral", pos:"CB", num:3, goals:0 },
    { name:"Çağlar Söyüncü", pos:"CB", num:4, goals:0 },
    { name:"Ferdi Kadıoğlu", pos:"LB", num:20, goals:0 },
    { name:"Zeki Çelik", pos:"RB", num:2, goals:0 },
    { name:"Uğurcan Çakır", pos:"GK", num:1, goals:0 },
  ]},

  // Group E
  GER: { coach:"Julian Nagelsmann", formation:"4-2-3-1", players:[
    { name:"Manuel Neuer", pos:"GK", num:1, goals:0 },
    { name:"Antonio Rüdiger", pos:"CB", num:2, goals:0 },
    { name:"Jonathan Tah", pos:"CB", num:4, goals:0 },
    { name:"Joshua Kimmich", pos:"RB", num:6, goals:0 },
    { name:"Maximilian Mittelstädt", pos:"LB", num:18, goals:0 },
    { name:"Jamal Musiala", pos:"AM", num:10, goals:0 },
    { name:"Florian Wirtz", pos:"AM", num:17, goals:0 },
    { name:"İlkay Gündoğan", pos:"CM", num:21, goals:0 },
    { name:"Leroy Sané", pos:"RW", num:19, goals:0 },
    { name:"Kai Havertz", pos:"ST", num:7, goals:0 },
    { name:"Serge Gnabry", pos:"LW", num:11, goals:0 },
    { name:"Niclas Füllkrug", pos:"ST", num:9, goals:0 },
    { name:"Pascal Groß", pos:"CM", num:5, goals:0 },
    { name:"Marc-André ter Stegen", pos:"GK", num:12, goals:0 },
  ]},
  CUW: { coach:"Dick Advocaat", formation:"4-3-3", players:[
    { name:"Leandro Bacuna", pos:"CM", num:8, goals:0 },
    { name:"Tahith Chong", pos:"RW", num:7, goals:0 },
    { name:"Juninho Bacuna", pos:"CM", num:10, goals:0 },
    { name:"Rangelo Janga", pos:"ST", num:9, goals:0 },
    { name:"Cuco Martina", pos:"RB", num:2, goals:0 },
    { name:"Eloy Room", pos:"GK", num:1, goals:0 },
    { name:"Jurich Carolina", pos:"CB", num:4, goals:0 },
  ]},
  CIV: { coach:"Emerse Faé", formation:"4-3-3", players:[
    { name:"Franck Kessié", pos:"CM", num:8, goals:0 },
    { name:"Amad Diallo", pos:"RW", num:11, goals:0 },
    { name:"Simon Adingra", pos:"LW", num:17, goals:0 },
    { name:"Nicolas Pépé", pos:"FW", num:19, goals:0 },
    { name:"Sébastien Haller", pos:"ST", num:9, goals:0 },
    { name:"Evan Ndicka", pos:"CB", num:3, goals:0 },
    { name:"Serge Aurier", pos:"RB", num:2, goals:0 },
    { name:"Yahia Fofana", pos:"GK", num:1, goals:0 },
    { name:"Ibrahim Sangaré", pos:"DM", num:6, goals:0 },
    { name:"Oumar Diakité", pos:"FW", num:14, goals:0 },
  ]},
  ECU: { coach:"Sebastián Beccacece", formation:"4-2-3-1", players:[
    { name:"Moisés Caicedo", pos:"DM", num:8, goals:0 },
    { name:"Piero Hincapié", pos:"CB", num:3, goals:0 },
    { name:"Kendry Páez", pos:"AM", num:10, goals:0 },
    { name:"Enner Valencia", pos:"ST", num:9, goals:0 },
    { name:"Gonzalo Plata", pos:"RW", num:11, goals:0 },
    { name:"Jeremy Sarmiento", pos:"LW", num:16, goals:0 },
    { name:"Willian Pacho", pos:"CB", num:4, goals:0 },
    { name:"Hernán Galíndez", pos:"GK", num:1, goals:0 },
    { name:"Ángelo Preciado", pos:"RB", num:2, goals:0 },
    { name:"Pervis Estupiñán", pos:"LB", num:7, goals:0 },
  ]},

  // Group F
  NED: { coach:"Ronald Koeman", formation:"4-3-3", players:[
    { name:"Virgil van Dijk", pos:"CB", num:4, goals:0 },
    { name:"Frenkie de Jong", pos:"CM", num:21, goals:0 },
    { name:"Cody Gakpo", pos:"LW", num:8, goals:0 },
    { name:"Memphis Depay", pos:"ST", num:10, goals:0 },
    { name:"Wout Weghorst", pos:"ST", num:9, goals:0 },
    { name:"Xavi Simons", pos:"AM", num:7, goals:0 },
    { name:"Matthijs de Ligt", pos:"CB", num:3, goals:0 },
    { name:"Denzel Dumfries", pos:"RB", num:22, goals:0 },
    { name:"Nathan Aké", pos:"LB", num:5, goals:0 },
    { name:"Bart Verbruggen", pos:"GK", num:1, goals:0 },
    { name:"Teun Koopmeiners", pos:"CM", num:14, goals:0 },
    { name:"Donyell Malen", pos:"RW", num:18, goals:0 },
    { name:"Tijjani Reijnders", pos:"CM", num:24, goals:0 },
  ]},
  JPN: { coach:"Hajime Moriyasu", formation:"3-4-2-1", players:[
    { name:"Takefusa Kubo", pos:"RW", num:11, goals:0 },
    { name:"Wataru Endo", pos:"DM", num:6, goals:0 },
    { name:"Takehiro Tomiyasu", pos:"CB", num:4, goals:0 },
    { name:"Daizen Maeda", pos:"LW", num:13, goals:0 },
    { name:"Kaoru Mitoma", pos:"AM", num:7, goals:0 },
    { name:"Hidemasa Morita", pos:"CM", num:5, goals:0 },
    { name:"Ayase Ueda", pos:"ST", num:9, goals:0 },
    { name:"Ko Itakura", pos:"CB", num:3, goals:0 },
    { name:"Hiroki Ito", pos:"CB", num:21, goals:0 },
    { name:"Zion Suzuki", pos:"GK", num:1, goals:0 },
    { name:"Ritsu Doan", pos:"FW", num:14, goals:0 },
    { name:"Ao Tanaka", pos:"CM", num:8, goals:0 },
    { name:"Yukinari Sugawara", pos:"RWB", num:2, goals:0 },
  ]},
  SWE: { coach:"Graham Potter", formation:"4-2-3-1", players:[
    { name:"Alexander Isak", pos:"ST", num:9, goals:0 },
    { name:"Viktor Gyökeres", pos:"ST", num:17, goals:0 },
    { name:"Anthony Elanga", pos:"RW", num:11, goals:0 },
    { name:"Dejan Kulusevski", pos:"AM", num:10, goals:0 },
    { name:"Emil Forsberg", pos:"LW", num:7, goals:0 },
    { name:"Mattias Svanberg", pos:"CM", num:8, goals:0 },
    { name:"Victor Lindelöf", pos:"CB", num:3, goals:0 },
    { name:"Isak Hien", pos:"CB", num:4, goals:0 },
    { name:"Ludwig Augustinsson", pos:"LB", num:6, goals:0 },
    { name:"Emil Holm", pos:"RB", num:2, goals:0 },
    { name:"Robin Olsen", pos:"GK", num:1, goals:0 },
  ]},
  TUN: { coach:"Jalel Kadri", formation:"4-3-3", players:[
    { name:"Ellyes Skhiri", pos:"DM", num:6, goals:0 },
    { name:"Hannibal Mejbri", pos:"CM", num:10, goals:0 },
    { name:"Elias Achouri", pos:"LW", num:7, goals:0 },
    { name:"Youssef Msakni", pos:"FW", num:11, goals:0 },
    { name:"Aïssa Laïdouni", pos:"CM", num:14, goals:0 },
    { name:"Montassar Talbi", pos:"CB", num:3, goals:0 },
    { name:"Dylan Bronn", pos:"CB", num:6, goals:0 },
    { name:"Bechir Ben Saïd", pos:"GK", num:1, goals:0 },
    { name:"Ali Abdi", pos:"LB", num:20, goals:0 },
    { name:"Wajdi Kechrida", pos:"RB", num:2, goals:0 },
  ]},

  // Group G
  BEL: { coach:"Domenico Tedesco", formation:"4-2-3-1", players:[
    { name:"Thibaut Courtois", pos:"GK", num:1, goals:0 },
    { name:"Kevin De Bruyne", pos:"AM", num:7, goals:0 },
    { name:"Romelu Lukaku", pos:"ST", num:9, goals:0 },
    { name:"Jérémy Doku", pos:"RW", num:11, goals:0 },
    { name:"Leandro Trossard", pos:"LW", num:17, goals:0 },
    { name:"Amadou Onana", pos:"DM", num:6, goals:0 },
    { name:"Youri Tielemans", pos:"CM", num:8, goals:0 },
    { name:"Wout Faes", pos:"CB", num:4, goals:0 },
    { name:"Zeno Debast", pos:"CB", num:2, goals:0 },
    { name:"Timothy Castagne", pos:"RB", num:21, goals:0 },
    { name:"Arthur Theate", pos:"LB", num:3, goals:0 },
    { name:"Loïs Openda", pos:"ST", num:10, goals:0 },
  ]},
  EGY: { coach:"Hossam Hassan", formation:"4-3-3", players:[
    { name:"Mohamed Salah", pos:"RW", num:10, goals:0 },
    { name:"Omar Marmoush", pos:"ST", num:9, goals:0 },
    { name:"Trézéguet", pos:"LW", num:7, goals:0 },
    { name:"Mohamed Elneny", pos:"CM", num:8, goals:0 },
    { name:"Ahmed Hegazi", pos:"CB", num:6, goals:0 },
    { name:"Ramy Rabia", pos:"CB", num:4, goals:0 },
    { name:"Ahmed Fathy", pos:"RB", num:2, goals:0 },
    { name:"Mohamed El Shenawy", pos:"GK", num:1, goals:0 },
    { name:"Emam Ashour", pos:"CM", num:14, goals:0 },
    { name:"Mostafa Mohamed", pos:"ST", num:11, goals:0 },
  ]},
  IRN: { coach:"Amir Ghalenoei", formation:"4-2-3-1", players:[
    { name:"Mehdi Taremi", pos:"ST", num:9, goals:0 },
    { name:"Alireza Beiranvand", pos:"GK", num:1, goals:0 },
    { name:"Saman Ghoddos", pos:"AM", num:10, goals:0 },
    { name:"Sardar Azmoun", pos:"ST", num:20, goals:0 },
    { name:"Ali Gholizadeh", pos:"RW", num:7, goals:0 },
    { name:"Saeid Ezatolahi", pos:"DM", num:6, goals:0 },
    { name:"Hossein Kanaanizadegan", pos:"CB", num:4, goals:0 },
    { name:"Ramin Rezaeian", pos:"RB", num:2, goals:0 },
    { name:"Ehsan Hajsafi", pos:"LB", num:3, goals:0 },
  ]},
  NZL: { coach:"Darren Bazeley", formation:"4-4-2", players:[
    { name:"Chris Wood", pos:"ST", num:9, goals:0 },
    { name:"Sarpreet Singh", pos:"AM", num:10, goals:0 },
    { name:"Liberato Cacace", pos:"LB", num:3, goals:0 },
    { name:"Marko Stamenić", pos:"CM", num:8, goals:0 },
    { name:"Matthew Garbett", pos:"CM", num:14, goals:0 },
    { name:"Ben Old", pos:"RW", num:7, goals:0 },
    { name:"Michael Boxall", pos:"CB", num:4, goals:0 },
    { name:"Nando Pijnaker", pos:"CB", num:5, goals:0 },
    { name:"Tim Payne", pos:"RB", num:2, goals:0 },
    { name:"Max Crocombe", pos:"GK", num:1, goals:0 },
  ]},

  // Group H
  ESP: { coach:"Luis de la Fuente", formation:"4-3-3", players:[
    { name:"Unai Simón", pos:"GK", num:1, goals:0 },
    { name:"Rodri", pos:"DM", num:16, goals:0 },
    { name:"Pedri", pos:"CM", num:8, goals:0 },
    { name:"Gavi", pos:"CM", num:9, goals:0 },
    { name:"Lamine Yamal", pos:"RW", num:19, goals:0 },
    { name:"Nico Williams", pos:"LW", num:10, goals:0 },
    { name:"Dani Olmo", pos:"AM", num:21, goals:0 },
    { name:"Álvaro Morata", pos:"ST", num:7, goals:0 },
    { name:"Dani Carvajal", pos:"RB", num:2, goals:0 },
    { name:"Aymeric Laporte", pos:"CB", num:14, goals:0 },
    { name:"Robin Le Normand", pos:"CB", num:3, goals:0 },
    { name:"Alejandro Grimaldo", pos:"LB", num:12, goals:0 },
    { name:"Mikel Oyarzabal", pos:"FW", num:11, goals:0 },
    { name:"Fabián Ruiz", pos:"CM", num:17, goals:0 },
  ]},
  CPV: { coach:"Pedro Brito", formation:"4-3-3", players:[
    { name:"Logan Costa", pos:"CB", num:4, goals:0 },
    { name:"Jamiro Monteiro", pos:"CM", num:10, goals:0 },
    { name:"Ryan Mendes", pos:"RW", num:7, goals:0 },
    { name:"Garry Rodrigues", pos:"LW", num:11, goals:0 },
    { name:"Bebé", pos:"FW", num:9, goals:0 },
    { name:"Deroy Duarte", pos:"CM", num:8, goals:0 },
    { name:"Vozinha", pos:"GK", num:1, goals:0 },
  ]},
  KSA: { coach:"Hervé Renard", formation:"4-2-3-1", players:[
    { name:"Salem Al Dawsari", pos:"LW", num:10, goals:0 },
    { name:"Firas Al Buraikan", pos:"ST", num:9, goals:0 },
    { name:"Mohamed Kanno", pos:"CM", num:8, goals:0 },
    { name:"Abdulelah Al-Amri", pos:"CB", num:5, goals:0 },
    { name:"Saud Abdulhamid", pos:"RB", num:2, goals:0 },
    { name:"Yasser Al-Shahrani", pos:"LB", num:3, goals:0 },
    { name:"Mohammed Al-Owais", pos:"GK", num:1, goals:0 },
    { name:"Abdullah Al-Hamdan", pos:"AM", num:11, goals:0 },
  ]},
  URU: { coach:"Marcelo Bielsa", formation:"4-3-3", players:[
    { name:"Federico Valverde", pos:"CM", num:15, goals:0 },
    { name:"Darwin Núñez", pos:"ST", num:11, goals:0 },
    { name:"Ronald Araújo", pos:"CB", num:4, goals:0 },
    { name:"José Giménez", pos:"CB", num:2, goals:0 },
    { name:"Sergio Rochet", pos:"GK", num:1, goals:0 },
    { name:"Manuel Ugarte", pos:"DM", num:5, goals:0 },
    { name:"Rodrigo Bentancur", pos:"CM", num:6, goals:0 },
    { name:"Giorgian de Arrascaeta", pos:"AM", num:10, goals:0 },
    { name:"Facundo Pellistri", pos:"RW", num:8, goals:0 },
    { name:"Maximiliano Araújo", pos:"LW", num:20, goals:0 },
    { name:"Nicolás de la Cruz", pos:"CM", num:7, goals:0 },
    { name:"Mathías Olivera", pos:"LB", num:16, goals:0 },
    { name:"Nahitan Nández", pos:"RB", num:14, goals:0 },
  ]},

  // Group I
  FRA: { coach:"Didier Deschamps", formation:"4-2-3-1", players:[
    { name:"Mike Maignan", pos:"GK", num:1, goals:0 },
    { name:"William Saliba", pos:"CB", num:2, goals:0 },
    { name:"Dayot Upamecano", pos:"CB", num:4, goals:0 },
    { name:"Jules Koundé", pos:"RB", num:5, goals:0 },
    { name:"Théo Hernandez", pos:"LB", num:22, goals:0 },
    { name:"N'Golo Kanté", pos:"DM", num:13, goals:0 },
    { name:"Aurélien Tchouaméni", pos:"DM", num:8, goals:0 },
    { name:"Antoine Griezmann", pos:"AM", num:7, goals:0 },
    { name:"Ousmane Dembélé", pos:"RW", num:11, goals:0 },
    { name:"Kylian Mbappé", pos:"LW", num:10, goals:0 },
    { name:"Randal Kolo Muani", pos:"ST", num:9, goals:0 },
    { name:"Eduardo Camavinga", pos:"CM", num:6, goals:0 },
    { name:"Kingsley Coman", pos:"FW", num:20, goals:0 },
    { name:"Bradley Barcola", pos:"FW", num:25, goals:0 },
  ]},
  SEN: { coach:"Pape Thiaw", formation:"4-3-3", players:[
    { name:"Édouard Mendy", pos:"GK", num:1, goals:0 },
    { name:"Kalidou Koulibaly", pos:"CB", num:3, goals:0 },
    { name:"Sadio Mané", pos:"LW", num:10, goals:0 },
    { name:"Nicolas Jackson", pos:"ST", num:9, goals:0 },
    { name:"Ismaïla Sarr", pos:"RW", num:7, goals:0 },
    { name:"Idrissa Gueye", pos:"DM", num:5, goals:0 },
    { name:"Pape Matar Sarr", pos:"CM", num:6, goals:0 },
    { name:"Abdou Diallo", pos:"CB", num:4, goals:0 },
    { name:"Moussa Niakhaté", pos:"CB", num:22, goals:0 },
    { name:"Krépin Diatta", pos:"RB", num:2, goals:0 },
    { name:"Fodé Ballo-Touré", pos:"LB", num:12, goals:0 },
    { name:"Habib Diallo", pos:"ST", num:19, goals:0 },
    { name:"Boulaye Dia", pos:"FW", num:11, goals:0 },
  ]},
  IRQ: { coach:"Graham Arnold", formation:"4-2-3-1", players:[
    { name:"Zidane Iqbal", pos:"CM", num:8, goals:0 },
    { name:"Ali Al-Hamadi", pos:"ST", num:9, goals:0 },
    { name:"Aymen Hussein", pos:"ST", num:10, goals:0 },
    { name:"Amir Al-Ammari", pos:"CM", num:6, goals:0 },
    { name:"Mohanad Ali", pos:"FW", num:11, goals:0 },
    { name:"Jalal Hassan", pos:"GK", num:1, goals:0 },
    { name:"Saad Natiq", pos:"CB", num:4, goals:0 },
    { name:"Ali Adnan", pos:"LB", num:3, goals:0 },
    { name:"Dhurgham Ismail", pos:"RB", num:2, goals:0 },
  ]},
  NOR: { coach:"Ståle Solbakken", formation:"4-3-3", players:[
    { name:"Erling Haaland", pos:"ST", num:9, goals:0 },
    { name:"Martin Ødegaard", pos:"AM", num:10, goals:0 },
    { name:"Alexander Sørloth", pos:"ST", num:19, goals:0 },
    { name:"Jens Petter Hauge", pos:"LW", num:11, goals:0 },
    { name:"Oscar Bobb", pos:"RW", num:20, goals:0 },
    { name:"Sander Berge", pos:"CM", num:8, goals:0 },
    { name:"Leo Østigård", pos:"CB", num:4, goals:0 },
    { name:"Kristoffer Ajer", pos:"CB", num:5, goals:0 },
    { name:"Julian Ryerson", pos:"RB", num:2, goals:0 },
    { name:"Fredrik Bjørkan", pos:"LB", num:3, goals:0 },
    { name:"Ørjan Nyland", pos:"GK", num:1, goals:0 },
    { name:"Antonio Nusa", pos:"FW", num:23, goals:0 },
  ]},

  // Group J
  ARG: { coach:"Lionel Scaloni", formation:"4-3-3", players:[
    { name:"Emiliano Martínez", pos:"GK", num:23, goals:0 },
    { name:"Cristian Romero", pos:"CB", num:13, goals:0 },
    { name:"Nicolás Otamendi", pos:"CB", num:19, goals:0 },
    { name:"Nahuel Molina", pos:"RB", num:2, goals:0 },
    { name:"Nicolás Tagliafico", pos:"LB", num:3, goals:0 },
    { name:"Enzo Fernández", pos:"CM", num:8, goals:0 },
    { name:"Alexis Mac Allister", pos:"CM", num:10, goals:0 },
    { name:"Rodrigo De Paul", pos:"CM", num:7, goals:0 },
    { name:"Lionel Messi", pos:"RW", num:10, goals:0 },
    { name:"Lautaro Martínez", pos:"ST", num:9, goals:0 },
    { name:"Julián Álvarez", pos:"ST", num:11, goals:0 },
    { name:"Ángel Di María", pos:"LW", num:21, goals:0 },
    { name:"Giovani Lo Celso", pos:"CM", num:16, goals:0 },
    { name:"Gonzalo Montiel", pos:"RB", num:4, goals:0 },
  ]},
  ALG: { coach:"Vladimir Petković", formation:"4-2-3-1", players:[
    { name:"Riyad Mahrez", pos:"RW", num:7, goals:0 },
    { name:"Rayan Aït-Nouri", pos:"LB", num:3, goals:0 },
    { name:"Houssem Aouar", pos:"AM", num:8, goals:0 },
    { name:"Ismaël Bennacer", pos:"CM", num:6, goals:0 },
    { name:"Amine Gouiri", pos:"ST", num:9, goals:0 },
    { name:"Ramy Bensebaini", pos:"CB", num:5, goals:0 },
    { name:"Aïssa Mandi", pos:"CB", num:4, goals:0 },
    { name:"Youcef Atal", pos:"RB", num:2, goals:0 },
    { name:"Anthony Mandrea", pos:"GK", num:1, goals:0 },
    { name:"Mohamed Amoura", pos:"FW", num:11, goals:0 },
  ]},
  AUT: { coach:"Ralf Rangnick", formation:"4-2-2-2", players:[
    { name:"David Alaba", pos:"CB", num:8, goals:0 },
    { name:"Marcel Sabitzer", pos:"CM", num:9, goals:0 },
    { name:"Marko Arnautović", pos:"ST", num:7, goals:0 },
    { name:"Christoph Baumgartner", pos:"AM", num:19, goals:0 },
    { name:"Konrad Laimer", pos:"CM", num:10, goals:0 },
    { name:"Michael Gregoritsch", pos:"ST", num:11, goals:0 },
    { name:"Nicolas Seiwald", pos:"DM", num:6, goals:0 },
    { name:"Kevin Danso", pos:"CB", num:4, goals:0 },
    { name:"Stefan Posch", pos:"RB", num:2, goals:0 },
    { name:"Phillipp Mwene", pos:"LB", num:3, goals:0 },
    { name:"Patrick Pentz", pos:"GK", num:1, goals:0 },
  ]},
  JOR: { coach:"Hussein Ammouta", formation:"4-4-2", players:[
    { name:"Musa Al-Taamari", pos:"RW", num:10, goals:0 },
    { name:"Yazan Al-Arab", pos:"CB", num:5, goals:0 },
    { name:"Yazid Abu Layla", pos:"GK", num:1, goals:0 },
    { name:"Ali Olwan", pos:"ST", num:9, goals:0 },
    { name:"Noor Al-Rawabdeh", pos:"CM", num:8, goals:0 },
    { name:"Mahmoud Al-Mardi", pos:"LW", num:11, goals:0 },
    { name:"Ehsan Haddad", pos:"RB", num:2, goals:0 },
    { name:"Mohammad Abu Hashish", pos:"LB", num:3, goals:0 },
    { name:"Abdallah Nasib", pos:"CB", num:4, goals:0 },
  ]},

  // Group K
  POR: { coach:"Roberto Martínez", formation:"4-3-3", players:[
    { name:"Diogo Costa", pos:"GK", num:1, goals:0 },
    { name:"Rúben Dias", pos:"CB", num:3, goals:0 },
    { name:"Gonçalo Inácio", pos:"CB", num:4, goals:0 },
    { name:"João Cancelo", pos:"LB", num:20, goals:0 },
    { name:"Nuno Mendes", pos:"RB", num:19, goals:0 },
    { name:"Bruno Fernandes", pos:"CM", num:8, goals:0 },
    { name:"Bernardo Silva", pos:"CM", num:10, goals:0 },
    { name:"João Palhinha", pos:"DM", num:6, goals:0 },
    { name:"Rafael Leão", pos:"LW", num:17, goals:0 },
    { name:"Cristiano Ronaldo", pos:"ST", num:7, goals:0 },
    { name:"Pedro Neto", pos:"RW", num:11, goals:0 },
    { name:"Vitinha", pos:"CM", num:23, goals:0 },
    { name:"Diogo Jota", pos:"FW", num:21, goals:0 },
    { name:"Gonçalo Ramos", pos:"ST", num:9, goals:0 },
  ]},
  COD: { coach:"Sébastien Desabre", formation:"4-2-3-1", players:[
    { name:"Aaron Wan-Bissaka", pos:"RB", num:2, goals:0 },
    { name:"Yoane Wissa", pos:"LW", num:7, goals:0 },
    { name:"Chancel Mbemba", pos:"CB", num:4, goals:0 },
    { name:"Cédric Bakambu", pos:"ST", num:9, goals:0 },
    { name:"Gaël Kakuta", pos:"AM", num:10, goals:0 },
    { name:"Samuel Moutoussamy", pos:"CM", num:8, goals:0 },
    { name:"Lionel Mpasi", pos:"GK", num:1, goals:0 },
    { name:"Arthur Masuaku", pos:"LB", num:3, goals:0 },
  ]},
  UZB: { coach:"Fabio Cannavaro", formation:"4-4-2", players:[
    { name:"Abdukodir Khusanov", pos:"CB", num:4, goals:0 },
    { name:"Eldor Shomurodov", pos:"ST", num:9, goals:0 },
    { name:"Jaloliddin Masharipov", pos:"AM", num:10, goals:0 },
    { name:"Otabek Shukurov", pos:"DM", num:6, goals:0 },
    { name:"Khojiakbar Alijonov", pos:"RB", num:2, goals:0 },
    { name:"Rustamjon Ashurmatov", pos:"CB", num:5, goals:0 },
    { name:"Utkir Yusupov", pos:"GK", num:1, goals:0 },
  ]},
  COL: { coach:"Néstor Lorenzo", formation:"4-2-3-1", players:[
    { name:"Luis Díaz", pos:"LW", num:7, goals:0 },
    { name:"James Rodríguez", pos:"AM", num:10, goals:0 },
    { name:"Daniel Muñoz", pos:"RWB", num:2, goals:0 },
    { name:"Jhon Durán", pos:"ST", num:9, goals:0 },
    { name:"Jefferson Lerma", pos:"DM", num:6, goals:0 },
    { name:"Yerry Mina", pos:"CB", num:3, goals:0 },
    { name:"Davinson Sánchez", pos:"CB", num:4, goals:0 },
    { name:"Johan Mojica", pos:"LB", num:17, goals:0 },
    { name:"Camilo Vargas", pos:"GK", num:1, goals:0 },
    { name:"Rafael Santos Borré", pos:"FW", num:11, goals:0 },
    { name:"Jhon Arias", pos:"RW", num:21, goals:0 },
    { name:"Richard Ríos", pos:"CM", num:8, goals:0 },
  ]},

  // Group L
  ENG: { coach:"Thomas Tuchel", formation:"4-2-3-1", players:[
    { name:"Jordan Pickford", pos:"GK", num:1, goals:0 },
    { name:"John Stones", pos:"CB", num:5, goals:0 },
    { name:"Marc Guéhi", pos:"CB", num:6, goals:0 },
    { name:"Trent Alexander-Arnold", pos:"RB", num:2, goals:0 },
    { name:"Luke Shaw", pos:"LB", num:3, goals:0 },
    { name:"Declan Rice", pos:"DM", num:4, goals:0 },
    { name:"Jude Bellingham", pos:"CM", num:10, goals:0 },
    { name:"Phil Foden", pos:"LW", num:11, goals:0 },
    { name:"Bukayo Saka", pos:"RW", num:7, goals:0 },
    { name:"Harry Kane", pos:"ST", num:9, goals:0 },
    { name:"Cole Palmer", pos:"AM", num:20, goals:0 },
    { name:"Conor Gallagher", pos:"CM", num:8, goals:0 },
    { name:"Ollie Watkins", pos:"ST", num:19, goals:0 },
    { name:"Kobbie Mainoo", pos:"CM", num:26, goals:0 },
    { name:"Anthony Gordon", pos:"FW", num:18, goals:0 },
  ]},
  CRO: { coach:"Zlatko Dalić", formation:"4-3-3", players:[
    { name:"Luka Modrić", pos:"CM", num:10, goals:0 },
    { name:"Joško Gvardiol", pos:"CB", num:4, goals:0 },
    { name:"Mateo Kovačić", pos:"CM", num:8, goals:0 },
    { name:"Andrej Kramarić", pos:"ST", num:9, goals:0 },
    { name:"Marcelo Brozović", pos:"DM", num:11, goals:0 },
    { name:"Mario Pašalić", pos:"CM", num:15, goals:0 },
    { name:"Josip Stanišić", pos:"RB", num:2, goals:0 },
    { name:"Borna Sosa", pos:"LB", num:3, goals:0 },
    { name:"Josip Šutalo", pos:"CB", num:6, goals:0 },
    { name:"Dominik Livaković", pos:"GK", num:1, goals:0 },
    { name:"Ivan Perišić", pos:"FW", num:14, goals:0 },
    { name:"Lovro Majer", pos:"AM", num:7, goals:0 },
  ]},
  GHA: { coach:"Otto Addo", formation:"4-2-3-1", players:[
    { name:"Thomas Partey", pos:"DM", num:5, goals:0 },
    { name:"Antoine Semenyo", pos:"ST", num:9, goals:0 },
    { name:"Iñaki Williams", pos:"RW", num:7, goals:0 },
    { name:"Mohammed Kudus", pos:"AM", num:10, goals:0 },
    { name:"Tariq Lamptey", pos:"RB", num:2, goals:0 },
    { name:"Alexander Djiku", pos:"CB", num:4, goals:0 },
    { name:"Gideon Mensah", pos:"LB", num:3, goals:0 },
    { name:"Lawrence Ati-Zigi", pos:"GK", num:1, goals:0 },
    { name:"Jordan Ayew", pos:"FW", num:11, goals:0 },
    { name:"Ernest Nuamah", pos:"LW", num:13, goals:0 },
  ]},
  PAN: { coach:"Thomas Christiansen", formation:"4-4-2", players:[
    { name:"Aníbal Godoy", pos:"CM", num:8, goals:0 },
    { name:"Adalberto Carrasquilla", pos:"CM", num:10, goals:0 },
    { name:"José Fajardo", pos:"ST", num:9, goals:0 },
    { name:"Ismael Díaz", pos:"LW", num:11, goals:0 },
    { name:"Yoel Bárcenas", pos:"RW", num:7, goals:0 },
    { name:"Fidel Escobar", pos:"CB", num:4, goals:0 },
    { name:"Michael Amir Murillo", pos:"RB", num:2, goals:0 },
    { name:"Eric Davis", pos:"LB", num:3, goals:0 },
    { name:"Orlando Mosquera", pos:"GK", num:1, goals:0 },
  ]}
};

// Helper
function getSquad(code) { return SQUADS[code] || null; }

// Position labels
const POS_LABELS = {
  "GK": "门将", "CB": "中后卫", "RB": "右后卫", "LB": "左后卫",
  "RWB": "右翼卫", "LWB": "左翼卫",
  "DM": "后腰", "CM": "中场", "AM": "前腰",
  "LW": "左边锋", "RW": "右边锋", "ST": "前锋", "FW": "攻击手"
};
